### PR TITLE
Correctly handle multiple profiles

### PR DESCRIPTION
**Pull request by p-davide**
Check for the default profile, and only use `Profile0` as a fallback.

### CODE REVIEW

**Comment by zefr0x** [comment]
Thank you for the pull request 👍.

I think that you should also support having multible firefox installations like `firefox-esr` or `firefox-dev`.

When someone has multible installations the `profiles.ini` file will be something like that:
```
[InstallIzFIX6IZbh5HBYwq]
Default=iZ5sIypS.dev-edition-default
Locked=1

[InstallzoYUx4sFkdKJRcJH]
Default=hABHEt6r.default-release
Locked=1

[Profile0]
Name=default-release
IsRelative=1
Path=hABHEt6r.default-release

[General]
StartWithLastProfile=1
Version=2

[Profile1]
Name=dev-edition-default
IsRelative=1
Path=iZ5sIypS.dev-edition-default
```

Those are the postfixes for firefox versions:
- .default-release
- .default-esr
- .dev-edition-default

I think that you need to check for the value of `Default` key and prioritize firefox versions, since with your implementation `firefox-dev` might be selected rather the the normal `firefox`.

**Comment by p-davide** [comment]
I tried installing `firefox-esr`, and it stores profiles in `.mozilla/firefox-esr` which we already don't check; do other versions behave differently?
Also, checking postfixes doesn't work if the profile has been renamed:
```ini
[Install4F96D1932A9F858E]
Default=n5k973lp.MyProfile
Locked=1

[Profile1]
Name=MyProfile
IsRelative=1
Path=n5k973lp.MyProfile
```

**Comment by zefr0x** [comment]
>I tried installing firefox-esr, and it stores profiles in .mozilla/firefox-esr which we already don't check; do other versions behave differently?

I'm using ArchLinux and I installed firefox-esr from the [AUR](https://aur.archlinux.org/packages/firefox-esr-bin) and it used the same `~/.mozilla/firefox/profiles.ini` file as the normal firefox. I have no idea about this behavior, but as long as we don't check the other file it will not make any problem for users that will have a behavior like your's.

>  Also, checking postfixes doesn't work if the profile has been renamed:

I used the dialog when running `firefox -P` to rename a profile and it just updated the `Name` value and not the `Path` or `Default` values.
Have you renamed it manualy? I don't think that it is the right way to rename it.

**Comment by zefr0x** [comment]
>  Have you renamed it manualy? I don't think that it is the right way to rename it.

Now that it tried to create a new profile, the prefix will be the profile's name.
So it will not work if you deleted the deafult profile and used a new one (not if you renamed the default profile).

In that case I think that it should fallback to `Profile0` and I should create a config file thing to select aother default profile rather then `Profile0`.

**Comment by p-davide** [comment]
I'm on Ubuntu, with Firefox from the mozillateam PPA.
I renamed it from `about:profiles`; creating a new profile, renaming it and setting it as default gives:
```ini
[Install4F96D1932A9F858E]
Default=ood6n56t.original-name
Locked=1

[Profile5]
Name=new-name
IsRelative=1
Path=ood6n56t.original-name
```
You were right in that renaming is not the issue (just check the Path).
However, user-created profiles still have no suffix (on my machine), so if someone on Arch uses the profile they created as default, we have no way to check if it comes from `firefox`, `firefox-esr` or `firefox-dev`.
Picking the first `[InstallXXXXXXXXXXXXXXXX]` that doesn't have `dev` or `esr`-specific suffixes works if profiles are stored in different folders _or_ the user didn't change the default profile (still an improvement).

**Comment by zefr0x** [comment]
What about this priority list?
1. `.default-release`
2. `.default-esr`
3. `.dev-edition-default`
4. The first `[InstallXXXXXXXXXXXXXXXX]`
5. A default value specified by the user in a config file
6. `Profile0`

I think that this should work gread for every user.

I will implement the config file part after merging your pull request as soon as I have a free time.

**Comment by p-davide** [comment]
I think a better order is:

1. A default value specified by the user in a config file (we shouldn't override the user's decision)
2. The first `[InstallXXXXXXXXXXXXXXXX]` without `esr` or `dev`
3. The first `[InstallXXXXXXXXXXXXXXXX]`
4. `.default-release` (must be below `[InstallXXXXXXXXXXXXXXXX]` for user-created profiles)
5. `.defaults-esr`
6. `.dev-edition-default`
7. `Profile0`

**Pull request closed without merging**
